{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "appointments-app.postgresql.name" . }}-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "appointments-app.postgresql.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgresql.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
{{- end }}