{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "appointments-app.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.ingress.tls.crt }}
  tls.key: {{ .Values.ingress.tls.key }}
{{- end }}
