apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-catalog-service
  labels:
    app: service-catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-catalog-service
  template:
    metadata:
      labels:
        app: service-catalog-service
    spec:
      containers:
      - name: service-catalog-service
        image: service-catalog-service:latest
        imagePullPolicy: IfNotPresent
        # image: matslo123/servicecatalogservice:0.1.0
        # imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8000"
        - name: DATABASE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: service-catalog-db-secret
              key: connection-string