apiVersion: batch/v1
kind: Job
metadata:
  name: migration-service-catalog-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration-service-catalog
        image: service-catalog-database-migrator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              key: migration-connection-string
              name: service-catalog-db-secret
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              key: db-username
              name: service-catalog-db-secret
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: service-catalog-db-secret
        - name: TARGET_MIGRATION
          value: $EXTERNAL_TARGET_MIGRATION # This has to be set externally. Empty means upgrade to latest version.