apiVersion: v1
kind: Service
metadata:
  name: service-catalog-service
spec:
  type: LoadBalancer
  selector:
    app: service-catalog-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http