apiVersion: v1
kind: Secret
metadata:
  name: availability-service-db-secret
  labels:
    app: availability-service
type: Opaque
data:
  # Host=shared-postgresql-service;Port=5432;Database=availabilitydb;Username=availabilitydb_user;Password=availabilitydb_password
  connection-string: SG9zdD1zaGFyZWQtcG9zdGdyZXNxbC1zZXJ2aWNlO1BvcnQ9NTQzMjtEYXRhYmFzZT1hdmFpbGFiaWxpdHlkYjtVc2VybmFtZT1hdmFpbGFiaWxpdHlkYl91c2VyO1Bhc3N3b3JkPWF2YWlsYWJpbGl0eWRiX3Bhc3N3b3Jk
  # Host=shared-postgresql-service;Port=5432;Database=availabilitydb;Username=postgres;Password=adminpassword
  migration-connection-string: SG9zdD1zaGFyZWQtcG9zdGdyZXNxbC1zZXJ2aWNlO1BvcnQ9NTQzMjtEYXRhYmFzZT1hdmFpbGFiaWxpdHlkYjtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1hZG1pbnBhc3N3b3Jk
  # availabilitydb_user
  db-username: YXZhaWxhYmlsaXR5ZGJfdXNlcg==
  # availabilitydb_password
  db-password: YXZhaWxhYmlsaXR5ZGJfcGFzc3dvcmQ=