apiVersion: v1
kind: Secret
metadata:
  name: booking-service-db-secret
  labels:
    app: booking-service
type: Opaque
data:
  # Host=shared-postgresql-service;Port=5432;Database=bookingdb;Username=bookingdb_user;Password=bookingdb_password
  connection-string: SG9zdD1zaGFyZWQtcG9zdGdyZXNxbC1zZXJ2aWNlO1BvcnQ9NTQzMjtEYXRhYmFzZT1ib29raW5nZGI7VXNlcm5hbWU9Ym9va2luZ2RiX3VzZXI7UGFzc3dvcmQ9Ym9va2luZ2RiX3Bhc3N3b3Jk
  # Host=shared-postgresql-service;Port=5432;Database=bookingdb;Username=postgres;Password=adminpassword
  migration-connection-string: SG9zdD1zaGFyZWQtcG9zdGdyZXNxbC1zZXJ2aWNlO1BvcnQ9NTQzMjtEYXRhYmFzZT1ib29raW5nZGI7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9YWRtaW5wYXNzd29yZA==
  # bookingdb_user
  db-username: Ym9va2luZ2RiX3VzZXI=
  # bookingdb_password
  db-password: Ym9va2luZ2RiX3Bhc3N3b3Jk
