apiVersion: v1
kind: Secret
metadata:
  name: service-catalog-db-secret
  labels:
    app: service-catalog-service
type: Opaque
data:
  # Host=shared-postgresql-service;Port=5432;Database=servicedb;Username=servicedb_user;Password=servicedb_password
  connection-string: SG9zdD1zaGFyZWQtcG9zdGdyZXNxbC1zZXJ2aWNlO1BvcnQ9NTQzMjtEYXRhYmFzZT1zZXJ2aWNlZGI7VXNlcm5hbWU9c2VydmljZWRiX3VzZXI7UGFzc3dvcmQ9c2VydmljZWRiX3Bhc3N3b3Jk
  # Host=shared-postgresql-service;Port=5432;Database=servicedb;Username=postgres;Password=adminpassword
  migration-connection-string: SG9zdD1zaGFyZWQtcG9zdGdyZXNxbC1zZXJ2aWNlO1BvcnQ9NTQzMjtEYXRhYmFzZT1zZXJ2aWNlZGI7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9YWRtaW5wYXNzd29yZA==
  # servicedb_user
  db-username: c2VydmljZWRiX3VzZXI=
  # servicedb_password
  db-password: c2VydmljZWRiX3Bhc3N3b3Jk
