apiVersion: v1
kind: Secret
metadata:
  name: user-service-db-secret
  labels:
    app: user-service
type: Opaque
data:
  # Host=shared-postgresql-service;Port=5432;Database=userdb;Username=userdb_user;Password=userdb_password
  connection-string: SG9zdD1zaGFyZWQtcG9zdGdyZXNxbC1zZXJ2aWNlO1BvcnQ9NTQzMjtEYXRhYmFzZT11c2VyZGI7VXNlcm5hbWU9dXNlcmRiX3VzZXI7UGFzc3dvcmQ9dXNlcmRiX3Bhc3N3b3Jk
  # Host=shared-postgresql-service;Port=5432;Database=userdb;Username=postgres;Password=adminpassword
  migration-connection-string: SG9zdD1zaGFyZWQtcG9zdGdyZXNxbC1zZXJ2aWNlO1BvcnQ9NTQzMjtEYXRhYmFzZT11c2VyZGI7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9YWRtaW5wYXNzd29yZA==
  # userdb_user
  db-username: dXNlcmRiX3VzZXI=
  # userdb_password
  db-password: dXNlcmRiX3Bhc3N3b3Jk
