apiVersion: v1
kind: Secret
metadata:
  name: shared-postgresql-secret
  labels:
    app: shared-postgresql
type: Opaque
data:
  # Base64 encoded admin credentials
  # adminpassword -> YWRtaW5wYXNzd29yZA==
  postgres-password: YWRtaW5wYXNzd29yZA==