apiVersion: v1
kind: Service
metadata:
  name: shared-postgresql-service
  labels:
    app: shared-postgresql
spec:
  type: ClusterIP
  selector:
    app: shared-postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    name: postgresql