apiVersion: batch/v1
kind: Job
metadata:
  name: migration-users-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migration-users
        image: user-database-migrator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              key: migration-connection-string
              name: user-service-db-secret
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              key: db-username
              name: user-service-db-secret
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: user-service-db-secret
        - name: TARGET_MIGRATION
          value: $EXTERNAL_TARGET_MIGRATION # This has to be set externally. Empty means upgrade to latest version.