apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-service
  labels:
    app: availability-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: availability-service
  template:
    metadata:
      labels:
        app: availability-service
    spec:
      containers:
      - name: availability-service
        image: availability-service:latest
        imagePullPolicy: IfNotPresent
        #image: matslo123/availabilityservice:0.1.0
        #imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8000"
        - name: DATABASE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: availability-service-db-secret
              key: connection-string