apiVersion: v1
kind: Service
metadata:
  name: availability-service
spec:
  type: ClusterIP
  selector:
    app: availability-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http